version: '3.8'

services:
  chat-server-1:
    build: .
    environment:
      - PORT=3001
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
    ports:
      - "3001:3001"
    networks:
      - chat-network

  chat-server-2:
    build: .
    environment:
      - PORT=3002
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
    ports:
      - "3002:3002"
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge 